package hu.advancedweb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ExamConfig service. Represents a row in the &quot;lms_ExamConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.advancedweb.model.impl.ExamConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.advancedweb.model.impl.ExamConfigImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExamConfig
 * @see hu.advancedweb.model.impl.ExamConfigImpl
 * @see hu.advancedweb.model.impl.ExamConfigModelImpl
 * @generated
 */
public interface ExamConfigModel extends BaseModel<ExamConfig> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a exam config model instance should use the {@link ExamConfig} interface instead.
     */

    /**
     * Returns the primary key of this exam config.
     *
     * @return the primary key of this exam config
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this exam config.
     *
     * @param primaryKey the primary key of this exam config
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this exam config.
     *
     * @return the ID of this exam config
     */
    public long getId();

    /**
     * Sets the ID of this exam config.
     *
     * @param id the ID of this exam config
     */
    public void setId(long id);

    /**
     * Returns the group ID of this exam config.
     *
     * @return the group ID of this exam config
     */
    public long getGroupId();

    /**
     * Sets the group ID of this exam config.
     *
     * @param groupId the group ID of this exam config
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this exam config.
     *
     * @return the company ID of this exam config
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this exam config.
     *
     * @param companyId the company ID of this exam config
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the questions of this exam config.
     *
     * @return the questions of this exam config
     */
    @AutoEscape
    public String getQuestions();

    /**
     * Sets the questions of this exam config.
     *
     * @param questions the questions of this exam config
     */
    public void setQuestions(String questions);

    /**
     * Returns the evaluator of this exam config.
     *
     * @return the evaluator of this exam config
     */
    @AutoEscape
    public String getEvaluator();

    /**
     * Sets the evaluator of this exam config.
     *
     * @param evaluator the evaluator of this exam config
     */
    public void setEvaluator(String evaluator);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(ExamConfig examConfig);

    public int hashCode();

    public CacheModel<ExamConfig> toCacheModel();

    public ExamConfig toEscapedModel();

    public String toString();

    public String toXmlString();
}
