package hu.advancedweb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExamAnswer service. Represents a row in the &quot;lms_ExamAnswer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.advancedweb.model.impl.ExamAnswerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.advancedweb.model.impl.ExamAnswerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExamAnswer
 * @see hu.advancedweb.model.impl.ExamAnswerImpl
 * @see hu.advancedweb.model.impl.ExamAnswerModelImpl
 * @generated
 */
public interface ExamAnswerModel extends BaseModel<ExamAnswer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a exam answer model instance should use the {@link ExamAnswer} interface instead.
     */

    /**
     * Returns the primary key of this exam answer.
     *
     * @return the primary key of this exam answer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this exam answer.
     *
     * @param primaryKey the primary key of this exam answer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this exam answer.
     *
     * @return the ID of this exam answer
     */
    public long getId();

    /**
     * Sets the ID of this exam answer.
     *
     * @param id the ID of this exam answer
     */
    public void setId(long id);

    /**
     * Returns the group ID of this exam answer.
     *
     * @return the group ID of this exam answer
     */
    public long getGroupId();

    /**
     * Sets the group ID of this exam answer.
     *
     * @param groupId the group ID of this exam answer
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this exam answer.
     *
     * @return the company ID of this exam answer
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this exam answer.
     *
     * @param companyId the company ID of this exam answer
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this exam answer.
     *
     * @return the user ID of this exam answer
     */
    public Long getUserId();

    /**
     * Sets the user ID of this exam answer.
     *
     * @param userId the user ID of this exam answer
     */
    public void setUserId(Long userId);

    /**
     * Returns the answers of this exam answer.
     *
     * @return the answers of this exam answer
     */
    @AutoEscape
    public String getAnswers();

    /**
     * Sets the answers of this exam answer.
     *
     * @param answers the answers of this exam answer
     */
    public void setAnswers(String answers);

    /**
     * Returns the date of this exam answer.
     *
     * @return the date of this exam answer
     */
    public Date getDate();

    /**
     * Sets the date of this exam answer.
     *
     * @param date the date of this exam answer
     */
    public void setDate(Date date);

    /**
     * Returns the exam config ID of this exam answer.
     *
     * @return the exam config ID of this exam answer
     */
    public Long getExamConfigId();

    /**
     * Sets the exam config ID of this exam answer.
     *
     * @param examConfigId the exam config ID of this exam answer
     */
    public void setExamConfigId(Long examConfigId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(ExamAnswer examAnswer);

    public int hashCode();

    public CacheModel<ExamAnswer> toCacheModel();

    public ExamAnswer toEscapedModel();

    public String toString();

    public String toXmlString();
}
