package hu.advancedweb.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import hu.advancedweb.model.ExamConfig;

import hu.advancedweb.service.ExamConfigLocalServiceUtil;

/**
 * The extended model base implementation for the ExamConfig service. Represents a row in the &quot;lms_ExamConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExamConfigImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExamConfigImpl
 * @see hu.advancedweb.model.ExamConfig
 * @generated
 */
public abstract class ExamConfigBaseImpl extends ExamConfigModelImpl
    implements ExamConfig {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a exam config model instance should use the {@link ExamConfig} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ExamConfigLocalServiceUtil.addExamConfig(this);
        } else {
            ExamConfigLocalServiceUtil.updateExamConfig(this);
        }
    }
}
